teste_equatorial:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('dbt_snowflake_account') }}"
      # User/password auth
      user: "{{ env_var('dbt_user') }}"
      password: "{{ env_var('dbt_password') }}"
      role: "{{ env_var('dbt_role') }}"
      database: "{{ env_var('dbt_database') }}"
      schema: "{{ env_var('dbt_schema') }}"
      warehouse: "{{ env_var('dbt_warehouse') }}"
      client_session_keep_alive: False