teste_equatorial:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "zd27083.us-east-2.aws"
      # User/password auth
      user: "airflow_user"
      password: "Senha@123"
      role: "AIRFLOW_ADMIN_RL"
      database: "AIRFLOW_DB"
      schema: "AIRFLOW_SCHEMA"
      warehouse: "AIRFLOW_WH"
      client_session_keep_alive: False